### PR TITLE
Feature/header extensions (closes #18)

### LINKED ISSUE #18: Minimize header file difference relative to R package
As discussed in #17 we can break changes down into a few manageable steps.

The first, and fairly simple one, would be to rename the header files from `*.hh` to `*.h`.  While the former is valid C++, it is less common in repos of extension packages.  I can submit a simple PR.

### PR DESCRIPTION
**Pull request by eddelbuettel**
This small PR renames the header files to end in `*.h`, and updates the includes accordingly.

(There is a little bit of whitespace change there as my emacs config will munge trailing whitespace. I should make it more polite to only do that on updated lines...)

### CODE REVIEW

**Review by nlarusstone — APPROVED** [review]
LGTM. I'd feel more comfortable once we have a unit test suite/CI running so that we can be sure we don't miss anything. Are you ok to wait to merge until we have CI?

**Comment by eddelbuettel** [comment]
I would prefer to proceed to have PRs cleanly after another.  You have a test binary now.  

Hooking that in from Travis is simple.  Maybe in the next PR?

In sum, I made this PR under the assumption it could and should get merged quickly.

**Comment by nlarusstone** [comment]
Ok, let's merge

**Comment by eddelbuettel** [comment]
Yay.  Being a timezone over I had to make dinner in the meantime. We could add a 'fourth' item for a quick (minimal) Travis run.  I have an older fork of another pure C++ project I could base that one.  I will try to double check to first have that work on my fork so you should then be able to see Travis CI build off it.   If I get there that is :)

**Comment by eddelbuettel** [comment]
And it even worked.  See https://travis-ci.org/eddelbuettel/corels/builds/623479408

You will need to setup Travis for your repo too.  Let me know if you need a hand.

**Pull request merged**
